
server:
  port: 8080
  servlet:
      context-path: /api/v4

mybatis:
  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.simba.fitmanager.dao
pagehelper:
  helperDialect: mysql

spring:
    datasource:
        url: jdbc:mysql://192.168.1.120:3306/simba?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: li199505280624
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
            mode: LEGACYHTML5
            cache: false
