
server:
  port: 8080
  servlet:
      context-path: /api/v4

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.simba.fitmanager.dao
pagehelper:
  helperDialect: mysql

spring:
    datasource:
#        url: jdbc:mysql://192.168.1.120:3306/simba?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#        username: root
#        password: li199505280624
#        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 10
        maxWait: 10000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        keepAlive: true
        removeAbandoned: true
        removeAbandonedTimeout: 80
        logAbandoned: true
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j,wall

        url: jdbc:mysql://localhost:3306/fitmanager?useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

    thymeleaf:
        mode: LEGACYHTML5
        cache: false

    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 192.168.248.133
        password:
        jedis:
          pool:
            max-active: 200
            max-idle: 10
            min-idle: 0
token:
    # token失效时间（不是refreshToken）(这是自定义的)(秒)
    expirationSeconds: 60
    # 默认7天登录有效(根据业务更改)
    validTime: 7

